language: node_js
node_js:
- '8'
- '10'
cache:
  yarn: true
script:
- yarn run lint
notifications:
  slack:
    secure: np7HDSwnl/LPafSpmurP1WMwC7fVeOkUkhf921zY08ICRlt1LkLhzHaus7aqEEwQiTwBXXRVTYmaWkIakFrEarEFGKly9vfpsWAibTfeRTZycXJcr7GPdgr3M3HmzaEGSGc4C/CsRJ/Swvq29MFUa0xTf1lZ+gBnMARoqDs5ODF321SLqfwge7k3G58P7ITK5OQ8QftEyXzSZ/Ar2Xb3oMlZZMKTbv9EREYO2ONFdG6KT6HiygZ2Ah9Dp34HbnmXA6nikbJWOWwPZvAfSf6hCtemSxAlicSWlcndN275VeM2Q+qCtIfFnRHUth1plR72x3d5N0O7E9RQp2J2RmceUMaH6NzK7oRZQZAirYZjvl6dw/BkprjnkLmk3cBVx0SuFK/DkWUwPwaNNoRzX3iFnrmFkRCw4LND5mBWC6Pmfb3Y/qtOC25kdIpzjVQG50yXNrXd9GMS1aSsyOHIlccBtB8/L7jzYGGi5hJTOeC7NVl/KIxk291s/XVHc+ZNsdNgMNvSNXJDxEph9Tt4xwtETla7ETejtgnwRzBedD1UeID0S7+PeU22Pt0jdb1YI5G7SVLllm8ZgnlcajlcUZTZ+mr/8S8L9wzt3NFOca3prWiORIR9EAFoWhqIhIxJFzaDyt0Xew8BsOEfP5SUxH6UkTBiSWnhhouhatHDzLC6p5c=
